"""Create Review Model

Revision ID: 0dc0a36052e3
Revises: 647b4c3de1e9
Create Date: 2025-03-03 16:29:42.299174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc0a36052e3'
down_revision = '647b4c3de1e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
